config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :articles
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :api do
    resources :sessions, only: :create
    resources :articles
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Slugable

  belongs_to :user

  enum status: [:draft, :published]

  validates :title, presence: true
  validates :text, presence: true
  validates :user, presence: true

  after_save :log_creation
  before_create :slugify
  before_save :check_if_publishing

  def to_param
    slug
  end

  def publishing?
    @publishing
  end

  private

  def log_creation
    logger.info("New article: #{title} created")
  end

  def slugify
    self.slug = to_slug(title)
  end

  def check_if_publishing
    @publishing = status_was == 'draft' && status == 'published'
  end
end

app/models/concerns/slugable.rb
module Slugable
  extend ActiveSupport::Concern

  def to_slug(str)
    value = str.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n, '').to_s
    value.gsub!(/[']+/, '')
    value.gsub!(/\W+/, ' ')
    value.strip!
    value.gsub!(' ', '-')
    value.gsub!('_', '-')
    value.downcase
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :articles, dependent: :destroy

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.from_token(token)
    User.find_by(email: decode_token(token)[0]['email'])
  end

  def token
    JWT.encode(token_payload,
               Rails.application.credentials.secret_key_base,
               'HS256')
  end

  private

  def token_payload
    {
      email: email,
      sub: id,
      iss: 'demo',
      exp: Time.now.to_i + 21600
    }
  end

  def self.decode_token(token)
    JWT.decode(token, Rails.application.credentials.secret_key_base, true,
               algorithm: 'HS256')
  end
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
    include Pundit

    before_action :authenticate_user!
    before_action :destroy_session
    rescue_from Pundit::NotAuthorizedError, with: :forbidden

    def destroy_session
      request.session_options[:skip] = true
    end

    protected

    def api_error(status: 500, errors: [])
      head(status) && return if errors.empty?
      render json: jsonapi_format(errors).to_json, status: status
    end

    def jsonapi_format(errors)
      return errors if errors.is_a?(String)
      errors_hash = {}
      errors.messages.each do |attribute, error|
        array_hash = []
        error.each { |e| array_hash << { attribute: attribute, message: e } }
        errors_hash.merge!(attribute => array_hash)
      end

      errors_hash
    end

    private

    def authenticate_user!
      head :unauthorized, 'WWW-Authenticate' => error_401_message unless current_user
    end

    def error_401_message
      msg = 'Bearer realm="example"'
      msg += ', error="invalid_token"' if request.env['HTTP_AUTHORIZATION']

      msg
    end

    def forbidden
      api_error(status: :forbidden)
    end
  end
end

app/controllers/api/articles_controller.rb
module Api
  class ArticlesController < Api::ApplicationController
    def index
      authorize Article
      @articles = policy_scope(Article)
    end
  end
end

app/controllers/api/sessions_controller.rb
module Api
  class SessionsController < Api::ApplicationController
    skip_before_action :authenticate_user!

    def create
      user = User.find_by(email: create_params[:email])
      return api_error(status: 401) unless user&.valid_password?(create_params[:password])

      @current_user = user
      render json: user_details, status: 201
    end

    private

    def user_details
      {
        user: {
          email: @current_user.email,
          token: @current_user.token
        }
      }
    end

    def create_params
      params.require(:user).permit(:email, :password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_back fallback_location: root_path,
                  alert: 'Permission denied'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_and_authorize_article,
                only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    authorize Article
    @articles = policy_scope(Article)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
        if @article.publishing?
          ArticleMailer.article_published_email(@article).deliver_later
          ArticleIndexerJob.perform_later(@article)
        end
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_and_authorize_article
      @article = Article.find_by(slug: params[:id])
      authorize @article
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :text, :status)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
        def #{provider}
          auth = request.env["omniauth.auth"]
          if auth.info.email.blank?
            flash[:alert] = I18n.t('omniauth.email_missing',
                                   provider: "#{provider}".capitalize)
            redirect_to new_user_session_path
          else
            @user = User.from_omniauth(auth)
            if @user.persisted?
              sign_in_and_redirect @user, event: :authentication
              set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
            else
              session["devise.#{provider}_data"] = env["omniauth.auth"]
              redirect_to root_url
            end
          end
        end
    }
  end

  [:facebook, :google_oauth2].each do |provider|
    provides_callback_for provider
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @now = Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
  = f.input :title
  = f.input :text
  = f.input :status, collection: Article.statuses.keys
  = f.button :submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%table
  %thead
    %tr
      %th Title
      %th Text
      %th Author email
      %th Status
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.text
        %td= article.user&.email
        %td= article.status
        %td
          - if policy(article).show?
            = link_to 'Show', article
        %td
          - if policy(article).edit?
            = link_to 'Edit', edit_article_path(article)
        %td
          - if policy(article).destroy?
            = link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Text:
  = @article.text
%p
  %b Author email:
  = @article.user&.email
%p
  %b Status:
  = @article.status

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/layouts/_flash.html.haml
#alerts
  - if alert
    .alert.alert-danger.alert-dismissible.fade.show{role: 'alert'}
      = alert
      %button.close{type: 'button', data: { dismiss: 'alert' }}
        %span{"aria-hidden" => "true"} &times;

  - elsif notice
    .alert.alert-primary.alert-dismissible.fade.show{role: 'alert'}
      = notice
      %button.close{type: 'button', data: { dismiss: 'alert' }}
        %span{"aria-hidden" => "true"} &times;

app/views/layouts/_head.html.haml
%head
  %title TutorialBlog
  = csrf_meta_tags

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.haml
!!! 5
%html
  = render 'layouts/head'
  %body
    %main.container{role: 'main'}
      = render 'layouts/flash'
      = yield

app/views/welcome/index.html.haml
%h1= t '.title'
.alert.alert-primary
  = icon 'calendar'
  = @now

- if user_signed_in?
  %p
    Welcome
    = current_user.email
  %small= link_to 'Logout', destroy_user_session_path,
    method: :delete, class: 'btn btn-danger'
- else
  = link_to 'Sign in', new_user_session_path, class: 'btn btn-success'
  = link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path,
    class: 'btn btn-success'
  = link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path,
    class: 'btn btn-success'